// Lyrics sincronizadas — "Consume" — Chase Atlantic

export interface LyricLine {
  time: number;
  text: string;
}

const lyrics: LyricLine[] = [
  { time: 13.86, text: "Alright, alright, whoa" },
  { time: 16.56, text: "Why you pointing at me with that knife?" },
  { time: 19.63, text: "I've been cutting corners all my life, girl" },
  { time: 22.94, text: "The terror doesn't blossom overnight, no" },
  { time: 26.84, text: "She's crawling through the city in a rampage" },
  { time: 30.22, text: "Pressing on her fingers 'til the bones break" },
  { time: 33.67, text: "There's blood all in her nose from the propane" },
  { time: 36.68, text: "But a needle to the skin will make the pain fade" },
  { time: 39.50, text: "Yeah, ah-ah, this is what I do, ah-ah" },
  { time: 45.14, text: "Take another bite, ah-ah" },
  { time: 48.40, text: "Big enough to chew" },
  { time: 52.87, text: 'She said, "Careful, or you\'ll lose it"' },
  { time: 56.36, text: "But, girl, I'm only human" },
  { time: 59.77, text: "And I know there's a blade where your heart is" },
  { time: 63.07, text: "And you know how to use it" },
  { time: 66.43, text: "And you can take my flesh if you want, girl" },
  { time: 69.70, text: "But, baby, don't abuse it" },
  { time: 72.94, text: 'These voices in my head screaming, "Run, now"' },
  { time: 76.31, text: "I'm praying that they're human" },
  { time: 79.03, text: "Rollin', rollin', rolling back your eyes through your mind like" },
  { time: 85.33, text: "Oh, woah, the pressure in the gland's tight" },
  { time: 92.04, text: "Yeah, woah, yeah, it's either kill or be killed like" },
  { time: 98.24, text: "Oh, woah, the blood is either poured or it's spilt like" },
  { time: 105.11, text: "Yeah, ah-ah, this is what I do, ah-ah" },
  { time: 110.96, text: "Take another bite, ah-ah" },
  { time: 114.28, text: "Big enough to chew" },
  { time: 118.36, text: 'She said, "Careful, or you\'ll lose it"' },
  { time: 122.09, text: "But, girl, I'm only human" },
  { time: 125.37, text: "And I know there's a blade where your heart is" },
  { time: 128.95, text: "And you know how to use it" },
  { time: 132.08, text: "And you can take my flesh if you want, girl" },
  { time: 135.54, text: "But, baby, don't abuse it" },
  { time: 138.62, text: 'These voices in my head screaming, "Run, now"' },
  { time: 141.72, text: "I'm praying that they're human" },
  { time: 145.68, text: "Alright, alright" },
  { time: 147.98, text: "Love you but you cannot spend the night, nah" },
  { time: 151.34, text: "I've been alone almost all my life, girl" },
  { time: 154.47, text: "And shit like that don't change up overnight" },
  { time: 158.85, text: "I let you sleep in my tee" },
  { time: 161.24, text: "Tell me the things that you don't normally tweet" },
  { time: 164.50, text: "Acid and LSD and smokin' blunts on the beach" },
  { time: 167.46, text: "69 down 69 so we can both get a piece, yeah" },
  { time: 171.71, text: "I've been cutting corners like my whole life" },
  { time: 174.67, text: "Backstabbing bitches tryna' kill me with the whole knife" },
  { time: 177.63, text: "Day I die will be the only day a nigga ghostwrite" },
  { time: 181.08, text: "When I go they'll treat me like a god if this shit goes right" },
  { time: 184.71, text: 'She said, "Careful, or you\'ll lose it"' },
  { time: 187.84, text: "But, girl, I'm only human" },
  { time: 191.52, text: "And I know there's a blade where your heart is" },
  { time: 194.81, text: "And you know how to use it" },
  { time: 198.16, text: "And you can take my flesh if you want, girl" },
  { time: 201.36, text: "But, baby, don't abuse it" },
  { time: 204.55, text: 'These voices in my head screaming, "Run, now"' },
  { time: 207.81, text: "I'm praying that they're human" },
  { time: 211.47, text: "Please understand that I'm trying my hardest" },
  { time: 214.72, text: "My head's a mess but I'm trying regardless" },
  { time: 218.29, text: "Anxiety is one Hell of a problem" },
  { time: 221.43, text: "She's latching onto me, I can't resolve it" },
  { time: 224.72, text: "It's not right, it's not fair, it's not fair, it's not fair" },
  { time: 232.27, text: "It's no fair, it's no fair" },
  { time: 235.59, text: "Oh, no, no, no" },
  { time: 239.73, text: "" },
  { time: 244.50, text: "Don't run, don't run" },
  { time: 248.01, text: "" },
];

export default lyrics;
