// Lyrics sincronizadas — "DIE FOR ME" — Chase Atlantic
// Timestamps do ficheiro LRC oficial

export interface LyricLine {
  time: number;
  text: string;
}

const lyrics: LyricLine[] = [
  { time: 0.38, text: "Ooh, oh, yeah" },
  { time: 4.48, text: "Ooh, oh, yeah, yeah" },
  { time: 7.63, text: "Ooh, oh, yeah" },
  { time: 12.00, text: "Yeah" },
  { time: 14.19, text: "Yeah, hit the gas, ignite it, she sniff gasoline" },
  { time: 19.02, text: "Throw it back in private, never on the screen, no" },
  { time: 22.72, text: "Love the passion, fire, high ass self-esteem, yeah" },
  { time: 26.02, text: 'So outlandish, she said, "Fuck me \'til I scream"' },
  { time: 29.72, text: "She at the top of her game" },
  { time: 31.37, text: "Couldn't give a flyin' fuck if I'm famous" },
  { time: 33.57, text: "Nothin' was ever the same" },
  { time: 35.02, text: "Chase in rotation, no Drake in her playlist" },
  { time: 37.32, text: "Fiendin' for money and fame" },
  { time: 38.72, text: "She's at a B, she's tryna reach A-list" },
  { time: 40.82, text: "She want her status to change" },
  { time: 42.37, text: "But out of respect, I'm keepin' it nameless" },
  { time: 44.27, text: "Come on over, baby, can you slide for me? Yeah" },
  { time: 47.92, text: "You know how I love it when you ride on me" },
  { time: 50.92, text: "Oh, Lord, I'm in the water, take a dive with me" },
  { time: 55.02, text: "Put it on your tongue and take a flight with me" },
  { time: 59.12, text: "Pull up, baby, I need you to slide on me, yeah" },
  { time: 62.77, text: "Jump inside the Jeep and take a drive with me" },
  { time: 65.72, text: "Good God, she's on the floor, rollin' her eyes at me" },
  { time: 69.92, text: "Once I get inside, she'll wanna die with me, yeah" },
  { time: 73.82, text: "Come on over, baby, won't you lie?" },
  { time: 77.57, text: "Cocaine in my system in the driver's seat" },
  { time: 80.72, text: "Oh, Lord, I feel the pressure, it's surroundin' me" },
  { time: 84.70, text: "I'm just tryna live my life and die in peace" },
  { time: 89.32, text: "Stop all the talkin', I'm wastin' my damn time" },
  { time: 92.77, text: "Yeah, she told me to stop it" },
  { time: 94.92, text: "She told me to sober up" },
  { time: 96.62, text: "Yeah, I told her I love it" },
  { time: 98.42, text: '"I don\'t give a fuck," yeah, baby, I doubt it' },
  { time: 102.50, text: "Baby, I doubt it" },
  { time: 105.00, text: "Fly with me" },
  { time: 107.47, text: "Parasailin', take a glide with me, yeah" },
  { time: 112.32, text: "Try for me" },
  { time: 114.97, text: "Keep the passion, keep on driving me" },
  { time: 118.22, text: "Pull up, baby, I need you to slide for me" },
  { time: 121.82, text: "You know how I love it when you ride on me" },
  { time: 124.87, text: "Oh, Lord, I'm in the water, take a dive with me, yeah" },
  { time: 129.17, text: "Put it on your tongue and take a flight with me" },
  { time: 132.93, text: "Pull up, baby, I need you to slide for me, yeah" },
  { time: 136.53, text: "Jump inside the Jeep and take a drive with me" },
  { time: 139.53, text: "Good God, she's on the floor, rollin' her eyes at me" },
  { time: 143.73, text: "Once I get inside, you'll wanna die with me" },
  { time: 150.69, text: "Baby" },
  { time: 152.91, text: "Baby, yeah" },
  { time: 155.01, text: "Once I get inside, she'll wanna die with me" },
  { time: 159.00, text: "Parasailin', take a glide with me, yeah" },
  { time: 163.91, text: "Oh, oh, oh, oh" },
  { time: 166.76, text: "Yeah, yeah, yeah, yeah" },
  { time: 168.76, text: "Yeah, yeah, yeah, yeah" },
  { time: 170.36, text: "Yeah, yeah, yeah, yeah" },
  { time: 172.16, text: "Yeah, yeah, yeah, yeah" },
  { time: 173.96, text: "Yeah, yeah, yeah, yeah" },
  { time: 176.56, text: "Baby" },
  { time: 179.06, text: "Drive with me" },
  { time: 180.86, text: "If I overdose, then will you die with me?" },
  { time: 184.16, text: "My darlin', lie for me" },
  { time: 187.71, text: "Put your left hand on the Bible, sell a lie" },
  { time: 196.40, text: "If I overdose, will you die with me, baby?" },
  { time: 206.81, text: "" },
];

export default lyrics;
